# Site settings
title: iwi's data playground 
email: iwi@tuta.io
description: > # this means to ignore newlines until "baseurl:"
        A simplified record of my struggles with data, statistics, programming, etc.
baseurl: "/blog/" # the subpath of your site, e.g. /blog/
url: "http://iwi.github.io" # the base hostname & protocol for your site
github_username: iwi 

# Build settings
markdown: kramdown
